In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from astropy.io import fits

In [13]:
spec_file = '/Users/yaroslav/Downloads/thaddaeus_delivery/2200530216/jspipe/js_ni2200530216_0mpu7_goddard_GTI2.jsgrp'

spec_hdul = fits.open(spec_file)
spec_data = np.array(spec_hdul[1].data)
spec_hdul[1].header['RESPFILE']
spec_hdul[1].header

XTENSION= 'BINTABLE'           / binary table extension                         
BITPIX  =                    8 / 8-bit bytes                                    
NAXIS   =                    2 / 2-dimensional binary table                     
NAXIS1  =                   12 /   width of table in bytes                      
NAXIS2  =                 1501 / number of rows in table                        
PCOUNT  =                    0 / size of special data area                      
GCOUNT  =                    1 / one data group (required keyword)              
TFIELDS =                    4 / number of fields in each row                   
COMMENT                                                                         
COMMENT  *** End of mandatory fields ***                                        
COMMENT                                                                         
COMMENT                                                                         
COMMENT  *** End of mandator

In [11]:
f = '/Users/yaroslav/Downloads/thaddaeus_delivery/nicer_d48_u250_350_1713073284.rmf'

hdul = fits.open(f)
data = np.array(hdul[1].data)
data['CHANNEL'], data['E_MIN'], data['E_MAX']

(array([   0,    1,    2, ..., 1498, 1499, 1500], dtype=int32),
 array([0.000e+00, 1.000e-02, 2.000e-02, ..., 1.498e+01, 1.499e+01,
        1.500e+01], dtype=float32),
 array([1.000e-02, 2.000e-02, 3.000e-02, ..., 1.499e+01, 1.500e+01,
        1.501e+01], dtype=float32))